# Generated by Django 5.1.2 on 2024-10-30 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coffee", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="coffee",
            name="drink",
            field=models.CharField(
                choices=[("H", "Hot"), ("C", "Cold"), ("N", "Normal")],
                default="N",
                max_length=1,
            ),
        ),
        migrations.CreateModel(
            name="Comment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("body", models.TextField()),
                (
                    "coffee",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="coffee.coffee"
                    ),
                ),
            ],
        ),
    ]
